### ISSUE TITLE
Look into time module.

### ISSUE THREAD

**Issue by baseplate-admin** [TanimSk/Face-Authenticator-WebApp#1]
Do you really need this function? 

https://github.com/TanimSk/Face-Authenticator-WebApp/blob/d053991cca68ab649dce8a30fe085b6fd4923e13/main/time_convertion.py#L1-L4

**Comment by TanimSk** [comment]
Yea

**Comment by baseplate-admin** [comment]
Low code quality

**Comment by baseplate-admin** [comment]
Fix your damn codes

**Comment by TanimSk** [comment]
How exactly its poor?
Maybe you're poor in mathematics

**Comment by baseplate-admin** [comment]
My dude doesn’t know `time.stfrtime` exists

**Comment by TanimSk** [comment]
Lol, what makes you think i donno?
Since its not a time object, i did mathematical operations. I didnt pollute my codes by writing same logic again.
I hope you understood
